[gmail]
from_name = "Luuk"
from_email = "poisonplay1811@gmail.com"
label = "outreach"

[campaign]
service_name = "AI Website Optimalisatie"
value_prop = "We helpen MKB bedrijven hun website te optimaliseren met AI voor meer leads en conversies."
cta = "Zou je interesse hebben in een gratis analyse van je huidige website?"

[openai]
api_key = ""
model = "gpt-4o-mini"
